### ISSUE TITLE
このリポジトリをtechbureauのアカウントにForkしても良いでしょうか？

### ISSUE THREAD

**Issue by RossyWhite** [palon7/zaif-ruby#2]
先日、先物取引のAPIをリリースまして、
これを機に色んな言語のラッパーをossで提供しようと思っているのですが、

一から作るのは大変なので、差し支えなければ、
[テックビューロのアカウント](https://github.com/techbureau)にforkしたいのですが、よろしいでしょうか？

**Comment by RossyWhite** [comment]
(実装もしていただけると、実はとてもうれしかったりします、)

**Comment by palon7** [comment]
LICENSE.txtの記述通り、MITライセンスに従っていただければ全く問題ありません。
よろしくお願いします。
